apiVersion: v1
kind: Service
metadata:
  name: book-api-service
  namespace: book-api
spec:
  type: NodePort
  selector:
    app: book-api
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
